# Generated by Django 3.1.6 on 2021-02-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studName', models.CharField(max_length=30)),
                ('studId', models.IntegerField()),
                ('studDept', models.CharField(max_length=30)),
                ('studYear', models.CharField(max_length=30)),
            ],
        ),
    ]
